### ISSUE TITLE
Provide example how to use with UIView

### ISSUE THREAD

**Issue by AndroidGecko** [shima11/PinchableImageView#1]
![screenshot 2019-02-26 at 11 56 08](https://user-images.githubusercontent.com/2511034/53407918-956c0f80-39bd-11e9-9289-0cfd7a20bf0d.png)

Getting above when trying case 1 (copy pasted example from README.md )

would be great if you could provide a working example for UIView.

Thanks!

**Comment by shima11** [comment]
Thank you for your comment.

What is the type of spiralContent?
`InteractiveZoomView.clone` is default implemention only for UIImageView.
So, please implement extension yourself or write closure directly.

I updated README.md and Demo. Please check.

**Comment by shima11** [comment]
@AndroidGecko
